from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("sites", "0001_initial"), ("subscribers", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Campaign", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=180)), ("campaign_type", models.CharField(choices=[("immediate", "Immediate"), ("weekly_signals", "Weekly Signals"), ("monthly_intelligence", "Monthly Intelligence")], default="weekly_signals", max_length=32)), ("description", models.TextField(blank=True)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="newsletter_campaigns", to="sites.site"))]),
        migrations.CreateModel(name="Edition", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("subject", models.CharField(max_length=200)), ("preview_text", models.CharField(blank=True, max_length=300)), ("content_markdown", models.TextField()), ("state", models.CharField(choices=[("draft", "Draft"), ("scheduled", "Scheduled"), ("sending", "Sending"), ("sent", "Sent"), ("cancelled", "Cancelled")], default="draft", max_length=20)), ("scheduled_at", models.DateTimeField(blank=True, null=True)), ("sent_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="editions", to="newsletters.campaign")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Delivery", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("state", models.CharField(choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")], default="queued", max_length=12)), ("provider_message_id", models.CharField(blank=True, max_length=200)), ("error_message", models.TextField(blank=True)), ("sent_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("edition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="newsletters.edition")), ("subscriber", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="subscribers.subscriber"))], options={"constraints": [models.UniqueConstraint(fields=("edition", "subscriber"), name="unique_delivery_per_edition")]})
    ]
