from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [("sites", "0001_initial"), ("sources", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("slug", models.SlugField()), ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="sites.site"))], options={"ordering": ["name"], "constraints": [models.UniqueConstraint(fields=("site", "slug"), name="unique_category_slug_per_site")]}),
        migrations.CreateModel(name="Series", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160)), ("slug", models.SlugField()), ("description", models.TextField(blank=True)), ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="series", to="sites.site"))]),
        migrations.CreateModel(name="Tag", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80)), ("slug", models.SlugField()), ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="sites.site"))], options={"ordering": ["name"], "constraints": [models.UniqueConstraint(fields=("site", "slug"), name="unique_tag_slug_per_site")]}),
        migrations.CreateModel(name="Article", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=240)), ("slug", models.SlugField(max_length=260)), ("excerpt", models.TextField()), ("content_markdown", models.TextField()), ("content_type", models.CharField(choices=[("signal", "Signal"), ("analysis", "Analysis"), ("field_note", "Field Note"), ("radar", "Radar"), ("living_article", "Living Article"), ("briefing", "Briefing")], default="signal", max_length=24)), ("state", models.CharField(choices=[("idea", "Idea"), ("researching", "Researching"), ("draft", "Draft"), ("review", "Review"), ("approved", "Approved"), ("scheduled", "Scheduled"), ("published", "Published"), ("archived", "Archived"), ("rejected", "Rejected")], default="idea", max_length=20)), ("meta_title", models.CharField(blank=True, max_length=240)), ("meta_description", models.CharField(blank=True, max_length=320)), ("editorial_notes", models.TextField(blank=True)), ("impact_score", models.PositiveSmallIntegerField(default=0)), ("maturity_score", models.PositiveSmallIntegerField(default=0)), ("adoption_score", models.PositiveSmallIntegerField(default=0)), ("risk_score", models.PositiveSmallIntegerField(default=0)), ("business_relevance_score", models.PositiveSmallIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("published_at", models.DateTimeField(blank=True, null=True)), ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles", to=settings.AUTH_USER_MODEL)), ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="articles.category")), ("series", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles", to="articles.series")), ("site", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="sites.site"))], options={"ordering": ["-published_at", "-created_at"], "constraints": [models.UniqueConstraint(fields=("site", "slug"), name="unique_article_slug_per_site")]}),
        migrations.CreateModel(name="ArticleSource", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("added_by_agent", models.BooleanField(default=False)), ("note", models.TextField(blank=True)), ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="articles.article")), ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="sources.source"))], options={"constraints": [models.UniqueConstraint(fields=("article", "source"), name="unique_article_source")]}),
        migrations.AddField(model_name="article", name="sources", field=models.ManyToManyField(related_name="articles", through="articles.ArticleSource", to="sources.source")),
        migrations.AddField(model_name="article", name="tags", field=models.ManyToManyField(blank=True, related_name="articles", to="articles.tag")),
    ]
